MobileShop/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileShop.Models;
using MobileShop.Models.ViewModel;
using PagedList;
using PagedList.Mvc;
namespace MobileShop.Controllers
{
    public class ItemsController : Controller
    {
        DtMobileShopDataContext data = new DtMobileShopDataContext();
        // GET: Items
        public ActionResult Detail(int id)
        {
            //listItem to show a list of color of product
            var listItem = from t in data.Products
                       join c in data.ProductColors on t.ProductId equals c.ProductId
                       where t.ProductId == id
                       select new ProductViewModel()
                       {
                           //Id = t.ProductId,
                           //Name = t.ProductName,
                           //Detail = t.Detail,
                           //Sale = t.Sale,
                           //Image = t.ImageProduct,
                           //Screen = t.Screen,
                           //Cpu = t.CPU,
                           //UpdateDate = t.UpdateDate,
                           //Quantity = t.Quantity,
                           //Type = t.ProductType.TypeName,
                           //Brand = t.Brand.BrandName,
                           Color = c.ColorName,
                           Price = c.Price,
                           Imagecolor = c.ImageColor,
                           IdColor = c.ColorId
                       };
            //get basic info
            Product item = data.Products.Where(t => t.ProductId == id).First();
            ViewData["idP"] = item.ProductId;
            ViewBag.Name = item.ProductName;
            ViewData["quantity"] = item.Quantity;
            ViewBag.Brand = item.Brand;
            //return list
            return View(listItem.ToList());
        }

        public ActionResult Detail_in_cart(int id, int idColor)
        {
            var listItem = from t in data.Products
                           join c in data.ProductColors on t.ProductId equals c.ProductId
                           where t.ProductId == id
                           select new ProductViewModel()
                           {
                               Color = c.ColorName,
                               Price = c.Price,
                               Imagecolor = c.ImageColor,
                               IdColor = c.ColorId
                           };
            Product item = data.Products.Where(t => t.ProductId == id).First();
            ViewData["idP"] = item.ProductId;
            ViewBag.Name = item.ProductName;
            ViewData["quantity"] = item.Quantity;
            ViewBag.Brand = item.Brand;
            //get ColorId to set which color product is checked
            ViewBag.ColorId = idColor;

            return View(listItem.ToList());
        }
        private List<ProductViewModel> TakeProductBrands(int id)
        {
            var lstProd = from p in data.Products
                          join pc in data.ProductColors on p.ProductId equals pc.ProductId
                          where p.BrandId == id
                          //orderby p.UpdateDate descending
                          select new
                          {
                              pId = p.ProductId,
                              imgColor = pc.ImageColor,
                              pName = p.ProductName,
                              nameColor = pc.ColorName,
                              pPrice = pc.Price,
                              cpu = p.CPU,
                              screen = p.Screen
                          };
            var list = new List<ProductViewModel>();
            foreach (var item in lstProd)
            {
                list.Add(new ProductViewModel
                {
                    Id = item.pId,
                    Imagecolor = item.imgColor,
                    Name = item.pName,
                    ColorName = item.nameColor,
                    Price = item.pPrice,
                    Cpu = item.cpu,
                    Screen = item.screen
                });
            }
            list.OrderByDescending(a => a.UpdateDate);
            return list;
        }
        private List<ProductViewModel> TakeProductTypes(int id)
        {
            var lstProd = from p in data.Products
                          join pc in data.ProductColors on p.ProductId equals pc.ProductId
                          where p.TypeId == id
                          //orderby p.UpdateDate descending
                          select new
                          {
                              pId = p.ProductId,
                              imgColor = pc.ImageColor,
                              pName = p.ProductName,
                              nameColor = pc.ColorName,
                              pPrice = pc.Price,
                              cpu = p.CPU,
                              screen = p.Screen
                          };
            var list = new List<ProductViewModel>();
            foreach (var item in lstProd)
            {
                list.Add(new ProductViewModel
                {
                    Id = item.pId,
                    Imagecolor = item.imgColor,
                    Name = item.pName,
                    ColorName = item.nameColor,
                    Price = item.pPrice,
                    Cpu = item.cpu,
                    Screen = item.screen
                });
            }
            list.OrderByDescending(a => a.UpdateDate);
            return list;
        }
        public ActionResult ItemsForType(int id, int? page)
        {
            int pageSize = 9;
            int pageNum = (page ?? 1);
            var items = TakeProductTypes(id);
            ViewData["TypeId"] = id;
            var titleName = data.ProductTypes.SingleOrDefault(t => t.TypeId == id);
            ViewData["TitleName"] = titleName.TypeName;
            return View(items.ToPagedList(pageNum, pageSize));
        }
        public ActionResult ItemsForBrand(int id, int? page)
        {
            int pageSize = 9;
            int pageNum = (page ?? 1);
            var items = TakeProductBrands(id);
            ViewData["BrandId"] = id;
            var titleName = data.Brands.SingleOrDefault(t => t.BrandId == id);
            ViewData["TitleName"] = titleName.BrandName;
            return View(items.ToPagedList(pageNum,pageSize));
        }
    }
}

MobileShop/Controllers/NewHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileShop.Models;
using PagedList;
using PagedList.Mvc;
using MobileShop.Models.ViewModel;

namespace MobileShop.Controllers
{
    public class NewHomeController : Controller
    {
        DtMobileShopDataContext data = new DtMobileShopDataContext();

        private List<ProductViewModel> TakeNewProducts()
        {
            var lstProd = from p in data.Products
                          join pc in data.ProductColors on p.ProductId equals pc.ProductId
                          //orderby p.UpdateDate descending
                          select new
                          {
                              pId = p.ProductId,
                              imgColor = pc.ImageColor,
                              pName = p.ProductName,
                              nameColor = pc.ColorName,
                              pPrice = pc.Price,
                              cpu = p.CPU,
                              screen = p.Screen
                          };
            var list = new List<ProductViewModel>();
            foreach(var item in lstProd)
            {
                list.Add(new ProductViewModel
                {
                    Id = item.pId,
                    Imagecolor = item.imgColor,
                    Name = item.pName,
                    ColorName = item.nameColor,
                    Price = item.pPrice,
                    Cpu = item.cpu,
                    Screen = item.screen
                });
            }
            //shuffle list products
            list = list.OrderBy(a => Guid.NewGuid()).ToList();
            return list;
        }

        // GET: NewHome
        public ActionResult Index( int ? page)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            var newProduct = TakeNewProducts();
            return View(newProduct.ToPagedList(pageNum,pageSize));
        }
        public ActionResult Slider()
        {
            return PartialView();
        }
        public ActionResult Types()
        {
            var typeP = from t in data.ProductTypes select t;
            return PartialView(typeP);
        }
        public class BrandQuantity{
            private int id, quantity;
            private string name;

            public int Id
            {
                get
                {
                    return id;
                }

                set
                {
                    id = value;
                }
            }

            public string Name
            {
                get
                {
                    return name;
                }

                set
                {
                    name = value;
                }
            }

            public int Quantity
            {
                get
                {
                    return quantity;
                }

                set
                {
                    quantity = value;
                }
            }
        }
        public ActionResult Brands()
        {
            var brand = from t in data.Brands select t;
            var list = new List<BrandQuantity>();
            foreach (var item in brand)
            {
                var quantity = data.Products.Count(a => a.BrandId == item.BrandId);
                list.Add(new BrandQuantity {
                    Id = item.BrandId,
                    Name = item.BrandName,
                    Quantity = quantity
                });
            }
            return PartialView(list);
        }
    }
}

MobileShop/Views/Cart/AcceptOrder.cshtml
@{
    ViewBag.Title = "AcceptOrder";
    Layout = "~/Views/Shared/_LayoutMobiePhone.cshtml";
}

<h2>Đơn hàng của quý khách đã được chúng tôi ghi nhận. Chúng tôi sẽ liên hệ với bạn trong thời gian sớm nhất và giao hàng đúng hạn.</h2>
<p>
    @Html.ActionLink("VỀ TRANG CHỦ", "Index", "NewHome")
</p>

MobileShop/Views/Cart/Cart.cshtml
@using MobileShop.Models;
@model List<ItemInCart>

@{
    ViewBag.Title = "Cart";
    Layout = "~/Views/Shared/_LayoutMobiePhone.cshtml";
}
@section OverridesStyles{
    <style>
        section#slider {
            display: none;
        }
        div#left-side{
            display: none;
        }
        div.padding-right{
            width: 100%;
        }
    </style>
}

<script src="/Scripts/jquery.js"></script>
<script>
    $(document).ready(function () {
        function updateTotalQuantity() {
            $.ajax({
                url: '@Url.Action("TotalQuantity", "Cart")',
                method: "POST",
                success: function (data) {
                    $("#total_quantity").html(data);
                }
            })
            return false;
        }

        function updateTotalPrice() {
            $.ajax({
                url: '@Url.Action("TotalPrice", "Cart")',
                method: "POST",
                success: function (data) {
                    $("#all_total_price").html(data);
                }
            })
            return false;
        }

        $("body").delegate(".cart_quantity_up", "click", function () {
            var id_p = $(this).attr('id_p');
            var id_color = $(this).attr('id_color');
            var qtt_parent = $(this).parent().find('.cart_quantity_input');
            var qtt_number = qtt_parent.val();
            qtt_number++; // +1 to add more 1 unit
            qtt_parent.attr('value', qtt_number);
            
            $.ajax({
                url: '@Url.Action("UpdateQuantity", "Cart")' + '?idP=' + id_p + '&idColor=' + id_color + '&quantity=' + qtt_number,
                method: "POST",
                success: function (data) {
                    $("#total_price_" + id_p + "-" + id_color).html(data);
                    updateTotalQuantity();
                    updateTotalPrice();
                }
            })
            return false;
        })

        $("body").delegate(".cart_quantity_down", "click", function () {
            var id_p = $(this).attr('id_p');
            var id_color = $(this).attr('id_color');
            var qtt_parent = $(this).parent().find('.cart_quantity_input');
            var qtt_number = qtt_parent.val();
            qtt_number--;
            if (qtt_number < 1)
                qtt_number = 1;
            qtt_parent.attr('value', qtt_number);

            $.ajax({
                url: '@Url.Action("UpdateQuantity", "Cart")' + '?idP=' + id_p + '&idColor=' + id_color + '&quantity=' + qtt_number,
                method: "POST",
                success: function (data) {
                    $("#total_price_" + id_p + "-" + id_color).html(data);
                    updateTotalQuantity();
                    updateTotalPrice();
                }
            })
            return false;
        })

        $("body").delegate(".cart_quantity_input", "keyup", function () {
            var id_p = $(this).attr('id_p');
            var id_color = $(this).attr('id_color');
            var qtt_parent = $(this).parent().find('.cart_quantity_input');
            var qtt_number = qtt_parent.val();
            if (qtt_number === "")
                qtt_number = 1;
            qtt_parent.value = qtt_number;

            $.ajax({
                url: '@Url.Action("UpdateQuantity", "Cart")' + '?idP=' + id_p + '&idColor=' + id_color + '&quantity=' + qtt_number,
                method: "POST",
                success: function (data) {
                    $("#total_price_" + id_p + "-" + id_color).html(data);
                    updateTotalQuantity();
                    updateTotalPrice();
                }
            })
            return false;
        })
    })

</script>

<section id="cart_items">
    <div class="container">
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li class="active">Shopping Cart</li>
            </ol>
        </div>
        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Sản phẩm</td>
                        <td class="description"></td>
                        <td class="price">Giá</td>
                        <td class="quantity">Số Lượng</td>
                        <td class="total">Thành Tiền</td>
                        <td></td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="cart_product">
                                <a href=""><img src="/images/products/@item.image" alt="" width="100"></a>
                            </td>
                            <td class="cart_description">
                                <h4><a href="">@item.name @item.color_name</a></h4>
                                <p>Web ID: 1089772</p>
                            </td>
                            <td class="cart_price">
                                <p>@String.Format("{0:0,0}", @item.price) VNĐ</p>
                            </td>
                            <td class="cart_quantity">
                                <div class="cart_quantity_button">
                                    <a class="cart_quantity_up" href="" id_p="@item.id" id_color="@item.idcolor"> + </a>
                                    <input class="cart_quantity_input" type="number" name="quantity" value="@item.quantity" autocomplete="off" size="2" 
                                        id_p="@item.id" id_color="@item.idcolor" min="1" 
                                        onkeydown="javascript: return event.keyCode == 69 || event.keyCode == 189 ? false : true">
                                    <a class="cart_quantity_down" href="" id_p="@item.id" id_color="@item.idcolor"> - </a>
                                </div>
                            </td>
                            <td class="cart_total">
                                <p id='total_price_@item.id-@item.idcolor' class="cart_total_price">@String.Format("{0:0,0}", @item.Total()) VNĐ</p>
                            </td>
                            <td class="cart_delete">
                                <a class="cart_quantity_delete" href="@Url.Action("Detail_in_cart","Items", new { id = item.id, idColor = item.idcolor})"><i class="fa fa-info"></i></a>
                            </td>
                            <td class="cart_delete">
                                <a class="cart_quantity_delete" href="@Url.Action("RemoveItem","Cart", new { idP = item.id, idColor = item.idcolor})"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot style="border-top:1px solid #ccc">
                    <tr>
                        <td></td>
                        <td></td>
                        <td>Tổng số lượng:</td>
                        <td id="total_quantity">@ViewBag.TotalQuantity</td>
                        <td>
                            <p class="cart_total_price" id="all_total_price">
                                @String.Format("{0:0,0}", ViewBag.TotalPrice)
                            </p>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="text-align: right">
                            @Html.ActionLink("XÓA GIỎ HÀNG", "DeleteCart", "Cart", new { @class = "btn btn-danger", @style = "margin-top: 10px" })
                        </td>
                        <td colspan="3" style="text-align: left">
                            @Html.ActionLink("ĐẶT HÀNG", "OrderCart", "Cart", new { @class = "btn btn-success", @style = "margin-top: 10px" })
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</section> <!--/#cart_items-->

MobileShop/Views/Cart/CartPartial.cshtml
<a href="@Url.Action("Cart","Cart")" id="cart_quantity">
    <i class="fa fa-shopping-cart"></i>Giỏ hàng <span id="round_quantity" style="border-radius: 50%;font-size: 14px;padding: 2px 8px;color: #fff;background: #696763;">@ViewBag.TotalQuantity</span>
</a>

MobileShop/Views/Cart/OrderCart.cshtml
@using MobileShop.Models
@model List<ItemInCart>

@{
    ViewBag.Title = "OrderCart";
    Layout = "~/Views/Shared/_LayoutMobiePhone.cshtml";
}
@section OverridesStyles{
    <style>
        section#slider {
            display: none;
        }

        div#left-side {
            display: none;
        }

        div.padding-right {
            width: 100%;
        }
    </style>
}

<h2 style="text-align: center">THÔNG TIN HÀNG HÓA</h2>

<section id="cart_items">
    <div class="container">
        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Sản phẩm</td>
                        <td class="description"></td>
                        <td class="price">Giá</td>
                        <td class="quantity">Số Lượng</td>
                        <td class="total">Thành Tiền</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                        <tr>
                            <td class="cart_product">
                                <a href=""><img src="/images/products/@item.image" alt="" width="100"></a>
                            </td>
                            <td class="cart_description">
                                <h4><a href="">@item.name @item.color_name</a></h4>
                                <p>Web ID: 1089772</p>
                            </td>
                            <td class="cart_price">
                                <p>@String.Format("{0:0,0}", @item.price) VNĐ</p>
                            </td>
                            <td class="cart_quantity">
                                <div class="cart_quantity_button">
                                    <input class="order_cart_quantity" type="text" name="quantity" value="@item.quantity" disabled>
                                </div>
                            </td>
                            <td class="cart_total">
                                <p id='total_price_@item.id-@item.idcolor' class="cart_total_price">@String.Format("{0:0,0}", @item.Total()) VNĐ</p>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot style="border-top:1px solid #ccc">
                    <tr>
                        <td></td>
                        <td></td>
                        <td>Tổng số lượng:</td>
                        <td id="total_quantity">@ViewBag.TotalQuantity</td>
                        <td>
                            <p class="cart_total_price" id="all_total_price">
                                @String.Format("{0:0,0}", ViewBag.TotalPrice)
                            </p>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</section>

<h2 style="text-align: center">THÔNG TIN ĐẶT HÀNG</h2>
@{
    User cus = (User)Session["Customer"];
}

<table align="center">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <tr style="height:40px">
            <td>Họ tên khách hàng:</td>
            <td style="font-weight:bold">@cus.UserName</td>
        </tr>
        <tr style="height:40px">
            <td>Địa chỉ:</td>
            <td style="font-weight:bold">@cus.UserAddress</td>
        </tr>
        <tr style="height:40px">
            <td>Điện thoại:</td>
            <td style="font-weight:bold">@cus.NPhone</td>
        </tr>
        <tr style="height:40px">
            <td>Ngày đặt:</td>
            <td style="font-weight:bold">@DateTime.Now.ToShortDateString()</td>
        </tr>
        <tr style="height:40px">
            <td>Ngày giao hàng:</td>
            <td style="font-weight:bold">
                <input type="date" name="DeliveryDay" />
            </td>
        </tr>
        <tr style="height:40px">
            <td colspan="2" align="center">
                <input type="submit" value="ĐỒNG Ý ĐẶT HÀNG" class="btn btn-success" style="margin: 20px 0" id="btn_submit_form" />
            </td>
            <td></td>
        </tr>
    }
</table>

MobileShop/Views/Cart/UpdateQuantity.cshtml
@String.Format("{0:0,0}", @Model) VNĐ